### ISSUE TITLE
Error while installing from npm

### ISSUE THREAD

**Issue by Somebi** [pkrumins/node-gif#15]
make: **\* [Release/obj.target/gif/src/async_animated_gif.o] Error 1
make: Leaving directory `/node_modules/gif/build'
gyp ERR! build error
gyp ERR! stack Error:`make`failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:784:12)
gyp ERR! System Linux 3.8.0-22-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/gif
gyp ERR! node -v v0.10.5
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok
npm ERR! gif@2.0.2 install:`node-gyp rebuild`
npm ERR!`sh "-c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the gif@2.0.2 install script.
npm ERR! This is most likely a problem with the gif package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls gif
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.0-22-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gif"
npm ERR! cwd /
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0

**Comment by pkrumins** [comment]
Please use node 0.8.x. I'm unable to fix this bug as I'm not familiar with 0.10.x.

**Comment by doggan** [comment]
:cry: Was excited to try and use this library but had the same issues during installation 2 years later. May try and look into this, as I'd love to use this package.
